apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cmscrm-db-pvc
  namespace: cmscrm
spec:
  storageClassName: default
  volumeName: cmscrm-db-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
